# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('User_name', models.CharField(max_length=4096)),
                ('Phone', models.CharField(max_length=4096)),
                ('Address', models.CharField(max_length=4096)),
                ('Password', models.CharField(max_length=4096)),
                ('Email', models.CharField(max_length=4096)),
            ],
        ),
    ]
